# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5af4f661c6270bbf1d41052181c1b4abbf1e7a8331fc85ed293b0836bcd51db44ceace77b626e83f1e104267ebbd5da1922934ff4e7494559ba0bed80ac3812

test:
  secret_key_base: f235842a7fd8c2323756d59c40667a1c8c33598c0b3a3101439893f716c9c416ed37f3aec41965843e6b511594bfe399ada98f12f2f71c59dbb8da67fd4ac2f2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
